### ISSUE TITLE
Mobs sometimes forget they're underwater

### ISSUE THREAD

**Issue by TerraKnight27** [HerrahStrings/packwiz-packs#28] opened 2023-11-13 02:56 UTC
I have seen mobs randomly behave like they're not underwater, even though they are
In my creative mode testing, I have made some observations:

The bug only triggered for me after traveling around the world for a while (unsure if it's from amount of chunks loaded or time spent in world)
The bug is only active in certain chunks, mobs can go from one chunk to another and their underwater state will change
I have seen this bug happen with: Cod, Salmon, Squid, Dolphin, Drowned, Guardian, although it is likely this happens with any mob
The bug resets upon exiting and re-entering the world

I have also noticed that I am able to jump while standing underwater, although I am unsure if this is a bug or part of a mod

**Comment by sleepingdragoninn** [comment] 2024-01-17 00:14
I can't reproduce this, have you been able to reproduce it since? And are there any mods added to the pack? (and which pack edition?)

**Comment by sleepingdragoninn** [comment] 2024-04-28 05:31
closing this for staleness

**Closed as not planned by sleepingdragoninn** 2024-04-28 05:31 UTC
Labels: bug
